[project]
name = "splat-init"
version = "0.1.0"
description = "Special course at DTU on integrating 360 degree cameras with Gaussian Splatting"
readme = "README.md"
authors = [
    { name = "sarphiv", email = "32750711+sarphiv@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "ipympl>=0.9.7",
    "ipython>=9.5.0",
    "joblib>=1.5.2",
    "lightning>=2.5.5",
    "loguru>=0.7.3",
    "matplotlib>=3.10.6",
    "pyqt6>=6.9.1",
    "rerun-sdk>=0.23.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "tyro>=0.9.31",
    "vggt",
    "wandb>=0.21.3",
]

[project.scripts]
splat-init = "splat_init:main"

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
vggt = { git = "https://github.com/facebookresearch/vggt.git", rev = "e56963328b7476e615ce8dda9164d381f8dc07a3" }
