# Install system packages
FROM nvidia/cuda:12.8.0-devel-ubuntu24.04

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    --mount=source=.python-version,target=.python-version,type=bind \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    sudo \
    wget \
    zip \
    ripgrep \
    nvtop \
    python$(cat .python-version)-dev \
    ffmpeg \
    libsm6 \
    libxext6 \
    '^libxcb.*-dev' \
    libx11-xcb-dev \
    libglu1-mesa-dev \
    libgl1 \
    libxrender-dev \
    libxi-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    libgtk-3-dev \
    zlib1g-dev \
    libeigen3-dev \
    libxinerama-dev \
    libxcursor-dev \
    linux-libc-dev \
    xorg-dev \
    pkg-config \
    build-essential \
    ninja-build \
    g++-14 \
    gcc-14


# Set up non-root user
RUN echo ubuntu ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/ubuntu && \
    chmod 0440 /etc/sudoers.d/ubuntu
USER ubuntu
WORKDIR /workspace


# Set up CLI
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.2.1/zsh-in-docker.sh)" -- \
    -p git \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -p jj \
    -p uv


# Set up environments
ENV XDG_RUNTIME_DIR=/tmp
ENV PYTHONUNBUFFERED=True
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ARG TORCH_CUDA_ARCH_LIST
ENV TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}
ENV PATH="/workspace/.venv/bin:$PATH"
ENV VCPKG_ROOT="/workspace/vendor/vcpkg"
COPY vendor/ vendor/
RUN sudo chown -R ubuntu:ubuntu /workspace/vendor
# C++ environment
RUN --mount=target=/home/ubuntu/.cache/vcpkg,uid=1000,gid=1000,type=cache,sharing=locked \
    # vcpkg
    sudo ./vendor/vcpkg/bootstrap-vcpkg.sh -disableMetrics && \
    # cmake
    mkdir /tmp/cmake_install && cd /tmp/cmake_install && \
    wget https://github.com/Kitware/CMake/releases/download/v4.2.1/cmake-4.2.1-Linux-x86_64.sh && \
    chmod +x cmake-4.2.1-Linux-x86_64.sh && \
    sudo ./cmake-4.2.1-Linux-x86_64.sh --skip-license --prefix=/usr/local && \
    cd /workspace && rm -rf /tmp/cmake_install
RUN --mount=target=/home/ubuntu/.cache/vcpkg,uid=1000,gid=1000,type=cache,sharing=locked \
    # LichtFeld Studio
    cd vendor/lichtfeld-studio && \
    cmake -B build -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 -DCMAKE_BUILD_TYPE=Release -G Ninja && \
    cmake --build build -- -j$(nproc) && \
    cd ..
# Python environment
RUN --mount=target=/home/ubuntu/.cache/uv,uid=1000,gid=1000,type=cache,sharing=locked \
    --mount=target=/home/ubuntu/.cache/torch/hub,uid=1000,gid=1000,type=cache,sharing=locked \
    --mount=source=.python-version,target=.python-version,type=bind \
    --mount=source=uv.lock,target=uv.lock,type=bind \
    --mount=source=pyproject.toml,target=pyproject.toml,type=bind \
    --mount=source=README.md,target=README.md,type=bind \
    --mount=source=src,target=src,type=bind \
    sudo chown ubuntu:ubuntu /home/ubuntu/.cache && \
    uv sync --frozen && \
    uv run vipe --version # Trigger build of everything and ViPE custom build

RUN sudo chown -R ubuntu:ubuntu /home/ubuntu/.cache
