# Install system packages
FROM nvidia/cuda:12.8.0-devel-ubuntu24.04

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    sudo \
    wget \
    ripgrep \
    nvtop \
    ffmpeg \
    libsm6 \
    libxext6 \
    '^libxcb.*-dev' \
    libx11-xcb-dev \
    libglu1-mesa-dev \
    libxrender-dev \
    libxi-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    libgtk-3-dev \
    zlib1g-dev \
    libeigen3-dev \
    build-essential \
    ninja-build


# Set up non-root user
RUN echo ubuntu ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/ubuntu && \
    chmod 0440 /etc/sudoers.d/ubuntu
USER ubuntu
WORKDIR /workspace


# Set up CLI
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.2.1/zsh-in-docker.sh)" -- \
    -p git \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -p jj \
    -p uv


# Set up Python environment
ENV XDG_RUNTIME_DIR=/tmp
ENV PYTHONUNBUFFERED=True
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ARG TORCH_CUDA_ARCH_LIST
ENV TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}
ENV PATH="/workspace/.venv/bin:$PATH"
COPY vendor/ vendor/
RUN --mount=target=/home/ubuntu/.cache/uv,uid=1000,gid=1000,type=cache,sharing=locked \
    --mount=target=/home/ubuntu/.cache/torch/hub,uid=1000,gid=1000,type=cache,sharing=locked \
    --mount=source=.python-version,target=.python-version,type=bind \
    --mount=source=uv.lock,target=uv.lock,type=bind \
    --mount=source=pyproject.toml,target=pyproject.toml,type=bind \
    --mount=source=README.md,target=README.md,type=bind \
    --mount=source=src,target=src,type=bind \
    sudo chown ubuntu:ubuntu /home/ubuntu/.cache && \
    sudo chown -R ubuntu:ubuntu vendor && \
    uv sync --locked && \
    vipe --version

RUN sudo chown -R ubuntu:ubuntu /home/ubuntu/.cache
